# name: Robot E2E 

# on:  
#   push:
#     branches:
#       - develop
      
#   # schedule:
#   #   - cron: '*/5 * * * *'  # This will run the workflow every day at 11:45 AM Thailand time (UTC+7)

# jobs: 
#   cypress-run: 
#     runs-on: ubuntu-latest

#     steps: 
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.10.6
  
#       - name: Show Python Path and Path
#         run: |
#           echo "Python Path: $PYTHONPATH"
#           echo "Path: $PATH"
  
#       - name: Show Python Version and Installed Libraries
#         run: |
#           python --version
#           pip list
      
#       - name: Install Dependencies
#         run: |
#           python -m pip install --upgrade pip        
#           pip install robotframework-browser
#           pip install rpaframework
#           echo "robotframework" > requirements.txt
#           echo "Browser" >> requirements.txt        
#           echo "RPA" >> requirements.txt
#           echo "PyYAML" >> requirements.txt
#           python -m pip install -r requirements.txt    
      
#       - name: Set up headless mode
#         run: |
#           echo "export PYTEST_BROWSER_HEADLESS=1" >> $GITHUB_ENV
    
#       - name: Run rfbrowser init
#         run: |
#            rfbrowser init

#       - name: Run Robot Framework tests
#         run: robot --outputdir ../results testSuite
#         env:
#           CYPRESS_RECORD_KEY: ${{ secrets.ROBOT_RECORD_KEY }}
