name: Robot E2E 

on:  
  push:
    branches:
      - develop
      
  # schedule:
  #   - cron: '*/5 * * * *'  # This will run the workflow every day at 11:45 AM Thailand time (UTC+7)

jobs: 
  cypress-run: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-node@v2
        with:
         python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-appiumlibrary
          pip install Appium-Python-Client
          pip install Appium

      - name: Start Appium Server
        run: |
          npm install -g appium  # Install Appium globally
          appium &  # Start the Appium server in the background
          sleep 5  # Give the server time to start

      - name: Run Robot Framework tests
        run: robot --outputdir ../results testSuite
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.ROBOT_RECORD_KEY }}
